# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

import base64
import hashlib
from pathlib import Path

import cbor2
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    PublicFormat,
    load_pem_public_key,
)
from cryptography.x509 import load_pem_x509_certificate

from pyscitt import crypto
from pyscitt.cli.validate import strip_uhdr, validate_transparent_statement
from pyscitt.verify import (
    COSE_HEADER_PARAM_VDS,
    VDS_CCF,
    StaticTrustStore,
    verify_cose_sign1,
    verify_transparent_statement,
)

from .infra.generate_ccf_profile_capsule import generate_capsule

# A self-consistent CCF-profile capsule generated by a live ledger in
# test/test_ccf_profile_receipts.py: the valid-es256 payload re-signed with a
# throwaway test CA, plus a CCF-profile receipt and service identity certificate.
CAPSULE_DIR = Path(__file__).parent / "test_vectors" / "ccf-profile-capsule"
STATEMENT = CAPSULE_DIR / "statement.cose"
RECEIPT = CAPSULE_DIR / "receipt.cose"
TRANSPARENT_STATEMENT = CAPSULE_DIR / "transparent-statement.cose"
SERVICE_IDENTITY = CAPSULE_DIR / "service-identity.pem"

ISSUER = "127.0.0.1:10131"


def test_ccf_profile_capsule_is_pinned():
    expected = {
        "statement.cose": "02ec7822cd91641c74ee0d125ad9b89fc6961400c6efb69ec9aff65f3b23d567",
        "receipt.cose": "c99df7dca6afaec13c35077cccad9abf50bf3bfd31bf947cfb13154154b35a51",
        "transparent-statement.cose": "11b6c1b0286df9591d8c15e182e89a5f582b739f28a0c2153d415bfd4867be34",
        "service-identity.pem": "3789967eedc96b4157455c39e00848d32c70e60900a180248e13f9aa35f409aa",
    }
    assert {
        name: hashlib.sha256((CAPSULE_DIR / name).read_bytes()).hexdigest()
        for name in expected
    } == expected


def test_ccf_profile_capsule_statement_signature():
    # The signed statement verifies against its embedded leaf certificate.
    header, _ = crypto.parse_cose_sign1(STATEMENT.read_bytes())
    signing_certificate = crypto.cert_der_to_pem(base64.b64decode(header["x5c"][0]))
    verify_cose_sign1(
        STATEMENT.read_bytes(), crypto.get_cert_public_key(signing_certificate)
    )


def test_ccf_profile_capsule_transparent_statement():
    transparent_statement = TRANSPARENT_STATEMENT.read_bytes()
    signed_statement = strip_uhdr(transparent_statement)

    # The receipt is embedded as a bstr at header label 394 and stripping it
    # recovers exactly the committed signed statement.
    assert cbor2.loads(transparent_statement).value[1] == {
        crypto.SCITTReceipts.identifier: [RECEIPT.read_bytes()]
    }
    assert signed_statement == STATEMENT.read_bytes()
    receipt = cbor2.loads(RECEIPT.read_bytes())
    assert cbor2.loads(receipt.value[0])[COSE_HEADER_PARAM_VDS] == VDS_CCF

    service_identity = load_pem_x509_certificate(SERVICE_IDENTITY.read_bytes())
    trust_store = StaticTrustStore(key=service_identity.public_key())
    assert verify_transparent_statement(
        transparent_statement, trust_store, signed_statement
    ) == [
        {
            "iss": ISSUER,
            "iat": 1784481567,
            "sigtxid": "2.15",
            "regtxid": "2.14",
        }
    ]


def test_validate_ccf_profile_capsule(capsys, tmp_path):
    service_identity = load_pem_x509_certificate(SERVICE_IDENTITY.read_bytes())
    service_key = tmp_path / "service-key.pem"
    service_key.write_bytes(
        service_identity.public_key().public_bytes(
            Encoding.PEM, PublicFormat.SubjectPublicKeyInfo
        )
    )
    validate_transparent_statement(TRANSPARENT_STATEMENT, service_key=service_key)
    out = capsys.readouterr().out.strip().splitlines()
    assert out[-1] == f"Statement is transparent: {TRANSPARENT_STATEMENT}"
    assert f"Verified receipt from issuer {ISSUER}" in out[0]


def test_generator_produces_valid_capsule():
    # A freshly generated capsule (new keys, different digests) is equally valid.
    capsule = generate_capsule()

    verify_cose_sign1(capsule.statement, capsule.signing_identity_pub)

    assert strip_uhdr(capsule.transparent_statement) == capsule.statement
    assert cbor2.loads(capsule.transparent_statement).value[1] == {
        crypto.SCITTReceipts.identifier: [capsule.receipt]
    }

    trust_store = StaticTrustStore(
        key=load_pem_public_key(capsule.log_key_pub.encode())
    )
    (details,) = verify_transparent_statement(
        capsule.transparent_statement, trust_store, capsule.statement
    )
    assert details["iss"].startswith("did:x509:0:sha256:")
